# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cb788db55d931ab14a7fe3a94114c924481ba7aa75400a7d456727117b88b8965288255d7042ff4f2d731a6c80c37e7cc0af25d651d8d63ea7caaf70ced612c5

test:
  secret_key_base: 8491a09195238c74002d0def4fd8453fe26d0d164ef4a9a95b9c245ee78acaf9abadbc70004d5699f0cc43bf520a554f48fa73147186f5377cdad9052673bf96

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
